# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Black and Blue and Full of Smiles
email: spencajones@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Spencer and I'm using this site for blogging and links to current projects.
  I'm learning to code and they say write about what you learn... plus I can't keep talking my
  girlfriend's ear off, the super glue just isn't working!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blackandblue.com" # the base hostname & protocol for your site
twitter_username: theman0123
github_username:  theman0123

# Build settings
markdown: kramdown
